apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-exam
  labels:
    app: abc-exam
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: abc-exam
  template:
    metadata:
      labels:
        app: abc-exam
    spec:
      containers:
        - name: abc-exam
          image: suzuran1995/abc:tagVersion
          ports:
            - containerPort: 8080
            - containerPort: 443
