apiVersion: v1
kind: Service
metadata:
  name: abc-example
  labels:
    name: abc-example
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: abc-example
  type: NodePort
