apiVersion: v1
kind: Service
metadata:
  name: abc-exam
  labels:
    name: abc-exam
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: abc-exam
  type: NodePort
